import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { Roboto } from 'next/font/google'
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
})
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`  antialiased flex`}
      >
        <Navbar />
        <main className="flex-1 p-8 h-[100vh] overflow-scroll">
          {children}
        </main>
      </body>
    </html>
  );
}
